### ISSUE TITLE
raw_input not defined

### ISSUE THREAD

**Issue by toothsy** [sybergeek/stop-wait-arq-demo#1]
hey i just cloned your project and after installing the prerequisites and running it according to the md file  it gave me this error
```
Traceback (most recent call last):
   File "test.py", line 22, in <module>
     dataset = raw_input("Enter dataframe to be sent : ")
 NameError: name 'raw_input' is not defined
```

**Comment by sybergeek** [comment]
'raw_input' is the common input method in python 2.x which was modified to 'input' in python 3.x and as Kivy as used in this project runs only on python 2.x. Make sure that you are running the file with python 2.7 only. If you have both python 2.x and python 3.x installed then default python may refer to python 3.x. To solve that issue try opening the python 2.7 IDLE and run the file "test.py" from there.

If there is anything else drop a comment.

**Comment by toothsy** [comment]
Yeah i was using python 3.x
my bad.
You can close this issue
